### ISSUE TITLE
Cross-browser optimization fails

### ISSUE THREAD

**Issue by kbi-user** [pagespeed/ngx_pagespeed#1027]
Hi,

nginx: 1.9.5
pagespeed: 1.9.32.10-beta

browsers:

    Firefox 41.0.2
    Chrome 46.0.2490.80 m

issue:
1. The website itself serves "wrong css". Esspecially the <img> width and height attributes are square (500x500), but the images themelf are rectangles (570x320). Basically images are resized according the css values (1:1) instead of the original image proportions (57:32).
2. Durign optimization the whole css "breaks". (font attributes are los; css not served,...)

---

Bug:
- During optimization, pagespeed apparently enters a "loop" - site becomes unresponsive, while the server is under huge CPU load.
- resize_rendered_image_dimensions doesnt properly recognize rendered image dimensions

**Comment by kbi-user** [comment]
The problematic css only contains one statement:
@import "css/styles.min.css";

Apparently pagespeed simply removes the import and therby drop the styles.min.css file.

**Comment by jmarantz** [comment]
A few bugs have been fixed, including a spin-loop in the memcached interface, in the latest beta: 1.9.32.10-7423.

Please upgrade to that and see if it fixes these issues.  

This fixes a spin-look (https://github.com/pagespeed/mod_pagespeed/issues/1048).  Note that's on the mod_pagespeed issues list, but the memcached interface code is shared.

The other bug looks like https://github.com/pagespeed/mod_pagespeed/issues/1068 which is also fixed in that release.

I am not understanding the bug about rendered_image_dimensions.  If you can give more details, please re-open.

**Comment by kbi-user** [comment]
The filter "resize_rendered_image_dimensions" should superceed "resize_image".
- Resize image basically looks for the css width and height and resizes accordingly resulting in stretches etc.
- Resize_rendered_image_dimension should discover the rendered size in the browser (without looking at css OR image attribute). 

In fact the filter resize_rendered_image_dimensions resizes an image exactly according the image dimension in the image attribute (html). 

This is different to documentation and actually leads to really bad results.

**Comment by jmarantz** [comment]
Can you provide an example where resize_rendered_dimensions is not working?

Our example appears to work:

http://modpagespeed.com/resize_rendered_dimensions/image_resize_using_rendered_dimensions.html?PageSpeed=on&PageSpeedFilters=resize_rendered_image_dimensions

**Comment by kbi-user** [comment]
Takes a day since I corrected the php-code of the theme. I will revert the changes and drop a life example.
