### ISSUE TITLE
Pagespeed interfering with 'Expires' directive

### ISSUE THREAD

**Issue by JoyceBabu** [pagespeed/ngx_pagespeed#1091]
The expires directive in the following configuration does not work when pagespeed is enabled. The cache control / Expires headers are removed when pagespeed is enabled.

	location = /res/astrovision/astrovision.html {
		expires 1M;
		try_files $uri @backend;
		# return 204;
	}

I was running nginx 1.9.6 + PS 1.9.32.10 until today and it was working fine. The issue started after I upgraded to nginx 1.9.9 + PS 1.10.33.2. If I disable PageSpeed, the headers are appearing correctly.

**Comment by jmarantz** [comment]
Hi Joyce,

This is for HTML files, right?  By default, PageSpeed tightens caching
headers on HTML files because (a) they are not fully optimized first time
through the system and (b) depending on the options you've set, they can be
user-agent-specific.

See https://developers.google.com/speed/pagespeed/module/downstream-caching
for more detail on the best way to cache HTML with PageSpeed.

-Josh

**Comment by JoyceBabu** [comment]
Thank you Joshua.

**Comment by JoyceBabu** [comment]
Does PageSpeed optimize HTML content in background, even when they are served 
- without any Cache-Control headers
- with no-cache headers

If so, how does PS determine if the page has changed or not? Does it generate a hash of every page?

**Comment by jmarantz** [comment]
PageSpeed does not optimize HTML in the background.  It optimizes HTML in
the foreground, on every request.  It optimizes images, css, and JS in the
background, because it can more easily cache the results.

**Comment by JoyceBabu** [comment]
Thank you for the clarification

How does PageSpeed decide on whether or not to send a purge request to downstream cache (once the background JS/CSS/Image optimization is over)? Does pagespeed remember all HTML requests served by it, and send cache purge request for all of them?

**Comment by jeffkaufman** [comment]
@JoyceBabu PageSpeed optimizes html in the foreground, but that might trigger some background rewrites like image optimization.  When all the background rewriting for a request has finished PageSpeed sends a PURGE to the downstream cache so the next request can get a more optimized page.

**Comment by JoyceBabu** [comment]
Thank you Jeff.

From what I understood from the Downstream cache documentation, pagespeed will serve the initial request will just basic HTML optimizations. The JS/CSS/Image urls are not rewritten, if the they are not already optimized/available in PS cache. PS will then start a background job for optimizing the resource, and when the optimization is complete it will send a purge request for the HTML file, so that it can be re-cached with the optimized resource urls. Am I correct?

**Comment by jeffkaufman** [comment]
Yes, that sounds right.

**Comment by JoyceBabu** [comment]
Does PageSpeed maintain a list of url that were served without full optimization, so that it can send the PURGE request when the resources are optimized?

**Comment by jeffkaufman** [comment]
> Does PageSpeed maintain a list of HTML urls that were served without full optimization, so that it can send the PURGE request when the resources are optimized?

Yes.  (Though instead of being a literal list it's something that will happen after a long chain of callbacks.)

> Does it note the Expires header along with the URL and send the PURGE request only for those pages that haven't expired, or does it ignore the cache control headers and send the PURGE header for all urls?

That would be possible, but it doesn't do that: it sends the PURGE regardless.  The idea is that background optimization should be much faster than expiration of the resource, so it wouldn't come up.  If the html resources have very short cache lifetimes (a few minutes) then it seems to me that you could just ignore the whole bit about PURGE and not set that up, because the html would be refreshed soon anyway.
