### ISSUE TITLE
[HELP] Pagespeed NGINX breaks website.

### ISSUE THREAD

**Issue by QuantumRevenger** [pagespeed/ngx_pagespeed#1168]
I'm with Sitegrounds Cloud Hosting platform and toggling on pagespeed with this configuration brings my site to a halt.

http://s28.postimg.org/5igmg74b1/screenshot.jpg
**[(https://exp.simplygrub.co.uk/])**

If you need any logs, please advise where to find them and I will ask Siteground support to provide them as a .zip that I can link to them here.

> They claim to be running 1.9.32.10-7423 which is over 6 months old, and won't update unless I upgrade to their dedicated package. To be honest, as a host, they're a bit disappointing for nearly £70 a month...

```
pagespeed FetchHttps enable;
pagespeed EnableFilters canonicalize_javascript_libraries;
pagespeed EnableFilters inline_google_font_css;
pagespeed EnableFilters combine_css,flatten_css_imports;
pagespeed EnableFilters prioritize_critical_css;
pagespeed EnableFilters rewrite_css,sprite_images;
pagespeed EnableFilters combine_javascript,rewrite_javascript;
pagespeed EnableFilters collapse_whitespace,trim_urls;
pagespeed EnableFilters convert_meta_tags,insert_dns_prefetch;
pagespeed EnableFilters remove_comments,remove_quotes;
pagespeed EnableFilters extend_cache,extend_cache_pdfs;
pagespeed EnableFilters local_storage_cache;
pagespeed EnableFilters rewrite_images,responsive_images,responsive_images_zoom,resize_images,lazyload_images,resize_mobile_images,inline_preview_images,inline_images,recompress_images;
pagespeed EnableFilters inline_css;
pagespeed CssInlineMaxBytes 2000;
pagespeed EnableFilters elide_attributes,inline_import_to_link;
```

UPDATE: (or not)
pagespeed EnableFilters rewrite_css,sprite_images;
pagespeed EnableFilters combine_javascript,rewrite_javascript;
- By removing these from the configuration my site now loads again...

UPDATE 2:
Users are still reporting my site does not load properly in Chrome... (Turning off pagespeed, fixes the problem.)

UPDATE 3:
The problem is exclusive to Chromium, why is pagespeed breaking Chrome?

**Comment by jmarantz** [comment]
I'm not sure if the 6-month-old version of PageSpeed is causing the
functional problem on your site.  I think it's more likely to be a
configuration.  However, I do think you should strongly urge SiteGround to
update PageSpeed because we have just issued an important security patch:
https://developers.google.com/speed/pagespeed/module/release_notes#release_1.9.32.14-stable

We can iterate with your configuration  E.g. Start with
  https://exp.simplygrub.co.uk/?PageSpeed=collapse_whitespace
and add filters one-by-one from there.  e.g.

https://exp.simplygrub.co.uk/?PageSpeed=collapse_whitespace,rewrite_javascript

See which filter causes the trouble.  One thing I noticed when visiting
your site is this console log message
"/_2x.data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAL4AAAAXCAYAAAC1Z/W7AAAA…nKYt2fk3mEX/hduWbE7821mFtYX+kTj8N8I6qqPEfwQYADOznsFtyHK5AAAAAElFTkSuQmCC:1
GET
https://exp.simplygrub.co.uk/_2x.data:image/png;base64,iVBORw0KGgoAAAANSUhE…z5nKYt2fk3mEX/hduWbE7821mFtYX+kTj8N8I6qqPEfwQYADOznsFtyHK5AAAAAElFTkSuQmCC
404 ()"

This looks to me like there is JavaScript on your site which is
manipulating the URLs in your img tags, and that our optimizations are
rewriting your img tags as base64 URLs, which are then being mangled by
JavaScript as shown above.   Does that seem plausible?

I think I eliminated this problem by turning off all image optimization:

https://exp.simplygrub.co.uk/?PageSpeedFilters=-inline_preview_images,-rewrite_images
However, you can probably just find which image is causing trouble and use
"pagespeed Disallow IMG_pattern" to have PageSpeed skip that image and
optimize the other ones.

-Josh

**Comment by QuantumRevenger** [comment]
Siteground identified the problematic filters:
`pagespeed EnableFilters inline_google_font_css;
pagespeed EnableFilters combine_css,flatten_css_imports;`

Caused as a result of outdated pagespeed, and have urged them to update but they're no overly concerned by the matter and are more interested in pushing sales that I don't need.

> "/_2x.data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAL4AAAAXCAYAAAC1Z/W7AAAA…nKYt2fk3mEX/hduWbE7821mFtYX+kTj8N8I6qqPEfwQYADOznsFtyHK5AAAAAElFTkSuQmCC:1
GET
https://exp.simplygrub.co.uk/_2x.data:image/png;base64,iVBORw0KGgoAAAANSUhE…z5nKYt2fk3mEX/hduWbE7821mFtYX+kTj8N8I6qqPEfwQYADOznsFtyHK5AAAAAElFTkSuQmCC
404 ()"

This message doesn't appear in my console log and no javascript is programmed to manipulate the urls in the img tags, does seem strange this happened for you. Maybe you could try again and see if the problem goes away?

**Comment by QuantumRevenger** [comment]
UPDATE 4: The solution is - if you want a reliable and updated version of page speed. Don't use Siteground. Even if you pay for a dedicated server, they won't help you.

**Comment by dkanchev** [comment]
Hi, @QuantumRevenger 

The Nginx Pagespeed module on your SiteGround cloud server has been upgraded to version 1.9.32.14-0. I also updated your SiteGround support ticket. Please check it and let me know if there is something else I can assist you with.
