### ISSUE TITLE
Can't rewirte js when tinymce is in it

### ISSUE THREAD

**Issue by Jurigag** [pagespeed/ngx_pagespeed#1174]
In my project i have this procedure:

backend(php) is combining all js files into one
pagespeed is minifing etc them

But for some reason pagespeed can't handle it if there is tinymce added to combined files. It looks like this:
https://www.grupaautowimar.pl/js/plugins/tinymce/tinymce.min.js

**Comment by jmarantz** [comment]
I'm not sure what's going on in the PHP script, or what the name of the PHP-combined URL is, but this might be related to https://github.com/pagespeed/mod_pagespeed/issues/38 and our handling of that, which was to blacklist URLs with these patterns:

    Disallow("*js_tinyMCE*");
    Disallow("*tiny_mce*");
    Disallow("*tinymce*");

It's probably also worth mentioning that PageSpeed can do the combination step itself, but I wouldn't expect that to work around this limitation.

**Comment by Jurigag** [comment]
As i wrote, php is just combining all js files into one - for example production.js - and that's it. Im using Phalcon framework, it's written i zephir(php-like language) there is source of method which is joining and creating js final file etc https://github.com/phalcon/cphalcon/blob/master/phalcon/assets/manager.zep#L293

So on pagespeed side there is no really tinymce file. Just if tinymce is joined into this one big file then this final file is not rewrited at all.

**Comment by jmarantz** [comment]
Can you try adding ?PageSpeedFilters=+debug to your HTML URL.  PageSpeed will then add an HTML comment near the script reference indicating what caused the optimization to be skipped.

**Comment by Jurigag** [comment]
```
<!--This script contains introspective JavaScript and is unsafe to replace.--><!--JS not inlined since it&#39;s bigger than 2048 bytes--><!--This script contains introspective JavaScript and is unsafe to replace.-->
```

**Comment by jmarantz** [comment]
This is what I thought.  Some patterns of JavaScript text in the referenced file look to PageSpeed like they might break if we rename the script.  We know that in this case, PageSpeed was being overly conservative because you have already renamed the file in your PHP script, and we probably are not making that worse by renaming it again.  You can override this safety feature by putting this in your configuration:
    pagespeed AvoidRenamingIntrospectiveJavascript off;

See https://developers.google.com/speed/pagespeed/module/restricting_urls#aris

**Comment by Jurigag** [comment]
Yea that did the job thank you.

**Comment by jmarantz** [comment]
I can't tell if it's safe in general to rename the file containing tiny_mce's source is safe.  Many years ago, when  pagespeed/mod_pagespeed#38 was reported, we thought it wasn't.  But back then it might have been some other bug, long since fixed.  It also might be that tiny_mce contains several distinct bits of functionality, some of which are safe to rename, some aren't.  You must be using only the ones that are safe to rename.

But in any case you are already renaming that, so I think this is no less safe than what you were doing with PHP .
