### ISSUE TITLE
Leverage browser caching

### ISSUE THREAD

**Issue by superdoret** [pagespeed/ngx_pagespeed#1229]
I'm tunning my site using pagespeed module on nginx. I'm trying to fix the warning "Leverage browser caching". This warning is facing on me on https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fspeed.agrofy.com%2F&tab=desktop

I noticed that my images does not work under pagespeed. For example if I try to see the headers on https://speed.agrofy.com i can see that the site is working under pagespeed module.

**Server: nginx/1.8.0
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: frontend=st8v11n7t9aokd0ktrp4ebjnm1; expires=Tue, 02-Aug-2016 19:02:22 GMT; Max-Age=604800; path=/; domain=speed.agrofy.com; HttpOnly; frontend_cid=dgFEwzV57JUSPxeE; expires=Tue, 02-Aug-2016 19:02:22 GMT; Max-Age=604800; path=/; domain=speed.agrofy.com; secure; httponly
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
Date: Tue, 26 Jul 2016 19:02:22 GMT
X-Page-Speed: 1.9.32.3-4448
Cache-Control: max-age=0, no-cache, no-store**

But if I try to see an specific image https://speed.agrofy.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/t/r/tractor-massey-ferguson-mf-7390-disponible-2015-8-11-19-33-30-0.jpg the header does not working under pagespeed module:

Server: nginx/1.8.0
Content-Type: image/jpeg
Content-Length: 10484
Connection: keep-alive
Vary: Accept-Encoding
Last-Modified: Tue, 26 Jul 2016 19:32:54 GMT
Etag: W/"PSA-aj-jounN-kC_b"
Date: Tue, 26 Jul 2016 19:33:07 GMT
Expires: Tue, 26 Jul 2016 19:38:07 GMT
Cache-Control: max-age=300

My config files have:
**etc/nginx/common/pagespeed.conf**
location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
        add_header "" "";
}

pagespeed ForceCaching on;

**mysite.config (Virtual Host)**
pagespeed EnableFilters extend_cache;

location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
                expires 1d;
                access_log off;
                add_header Cache-Control "public";
 }

On my nginx log file I noticed that error:
2016/07/26 19:27:59 [warn] 3047#0: [ngx_pagespeed 1.9.32.3-4448] [0726/192759:WARNING:google_message_handler.cc(38)] 'ForceCaching' is global and is ignored at this scope

Any ideas? Thanks in advance!

**Comment by oschaaf** [comment]
Re: PSI complaining about "Leverage browser caching":
This probably was transient, I tested two times and the error was gone. ngx_pagespeed needs some time and traffic to get up to speed and fully optimize pages.

Re: specific image .. header does not working under pagespeed module
I see `Etag: W/"PSA-aj-jounN-kC_b"` which is written by ngx_pagespeed. You get at least some optimization here. It's written with a short cache control header of 5 minutes because ngx_pagespeed is not done optimizing the image yet. This is transient and should resolve after some time.

Re: ForceCaching
The warning is trying to tell you that ForceCaching needs to specified in a `http {}` block, you cannot specify it in a `server{}` block. 
Please be careful with this option though, it was meant for experimental purposes only. It is not recommended to serve live traffic with this option enabled.

Closing this issue - but if you have more questions, please do not hesitate to post them at https://groups.google.com/forum/#!forum/ngx-pagespeed-discuss

**Comment by superdoret** [comment]
I have right. I did wait some time and I can see some resources cached. 

But after wait 12 hours I still can see some resources that is not caching. if you want see that please check this on https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fspeed.agrofy.com%2F&tab=desktop

for example: https://speed.agrofy.com/skin/frontend/fyo/fyo/images/agrofy.png

I continue trying figure out this issue. Maybe that is because I have something wrong on my configuration files. 

Thanks in advance!

**Comment by oschaaf** [comment]
https://speed.agrofy.com/skin/frontend/fyo/fyo/images/agrofy.png indeed seems to be served in place with `Cache-Control: max-age=300`

However, I just noticed that you are using ngx_pagespeed version `1.9.32.3-4448` and there have been numerous fixes since that release:
https://developers.google.com/speed/pagespeed/module/release_notes

I would recommend upgrading.

**Comment by superdoret** [comment]
to upgrade to the latest version, I need to compile again nginx with page speed? or I have some "easy way" to upgrade?

**Comment by oschaaf** [comment]
If you installed by building from source last time, that is your path to upgrading as well.
