### ISSUE TITLE
Problem with webp support

### ISSUE THREAD

**Issue by chuxuanvinh** [pagespeed/ngx_pagespeed#1347]
When I enable webp with: convert_jpeg_to_webp, convert_to_webp_lossless, convert_to_webp_animated, recompress_webp, some pages (https://www.ihcm.vn/nghiep-vu/danh-gia.html) can not display image by some browsers, which do not support webp format (example Microsoft Edge or Firefox). The problem is the images returned are in always webp format even though the exptentions is png, jpeg,...
So we have to disable webp support.
Our topology is TLS -> Cache -> ZIP -> Pagespeed -> Backend

**Comment by oschaaf** [comment]
Do you have downstream caching set up?: https://developers.google.com/speed/pagespeed/module/downstream-caching

**Comment by chuxuanvinh** [comment]
Yes

**Comment by jmarantz** [comment]
If you want to use downstream caching with webp transcoding, you'll need to
avoid rewriting image URLs.  Otherwise the HTML cache will capture
rewritten '".webp" URLs and serve them to non-webp-accepting clients.

See
https://developers.google.com/speed/pagespeed/module/config_filters#preserveurls
or more generally,
https://developers.google.com/speed/pagespeed/module/optimize-for-bandwidth

A minimal fix:
  pagespeed ImagePreserveURLs on;

With this setting, the image URLs will not be rewritten, but the image
content can be transcoded to webp.  You will also need to ensure that your
proxy cache (and any CDNs you use) handles "Vary:Accept" properly.  See
this page for more details.

https://developers.google.com/speed/pagespeed/module/reference-image-optimize#AllowVaryOn

Good luck & happy holidays,
-Josh

**Comment by chuxuanvinh** [comment]
Hi Josh,
I will try your solution, but it may not solve the problems, because based on if brower support webp or not support webp, I have different cache key, so for non webp client, there is no .webp extentions resources, but I still saw image/webp content type, so client can not display picture.
Happy holidays
Vinh

**Comment by chuxuanvinh** [comment]
The problem is not solved.
This site https://www.ihcm.vn does not work as expected for some pages (Not every pages), example https://www.ihcm.vn/nghiep-vu/danh-gia.html
Even though I disable convert_jpeg_to_webp, convert_to_webp_lossless, convert_to_webp_animated, recompress_webp, but in the page https://www.ihcm.vn/nghiep-vu/danh-gia.html still have some resource with webp extentions (Example https://www.ihcm.vn/images/HCM_Articles/2014/05/xDanh-gia-iHCM-8.jpg.pagespeed.ic.dcn1Rh_XDH17llrzP9lF.webp) when I use Firefox, but content type is "image/jpeg".

**Comment by jmarantz** [comment]
It looks to me like my suggestion still hasn't taken effect on your site.  If you turned on either ImagePreserveUrls or OptimizeForBandwidth, you would not see HTML rewritten like this:

```
    <img alt="Ông Nguyễn Hồng Hải - Phó Giám đốc" src="images/Website2016/Khachhang/xNguyen-Hong-Hai-VDC-iHCM.png.pagespeed.ic.U-i8BAMBrc.png" width=260 height=184 />
```

I wonder if this is related to your downstream caching.  Maybe you have an older version of the pagespeed-rewritten HTML stored in your cache, so the changes I suggested have not made it out of your network yet.  Can you try flushing your downstream cache and see if that solves the problem?

**Comment by chuxuanvinh** [comment]
Downstream cache had been flushed when I tested the system.
Nothing changed when I turn on ImagePreserveUrls, so I have turned it off.

**Comment by chuxuanvinh** [comment]
Solved, this is a mistake from the editor. She copy and paste web page
