### ISSUE TITLE
Rewrite issue with CDN

### ISSUE THREAD

**Issue by wigald** [pagespeed/ngx_pagespeed#1384]
Hi,

I'm using ngx_pagespeed with nginx in front of IIS servers. 
Images are loaded from an external cdn.
When I allow pagespeed to cache those images it loads the images the first time but then ran into problems with rewriting the images.

Look here:

`https://cdn2.xxxx.de/images/xxx/xxx/xxx-xxx-si.png.pagespeed.ic.vSIb3ZTTd5.webp`

Of course this leads to a 404 because the cdn does not serve images via pagespeed.

Is there a way to take the images from the nginx in front of the website ?

I'm running on nginx 1.11.10 and pagespeed version 1.12.34.2-0

**Comment by oschaaf** [comment]
How did the original (non-pagespeed) versions of images end up at `cdn2.xxx.de`?
Did the CDN fetch them from your website, or did you upload them manually?

**Comment by wigald** [comment]
Hi,

what do you mean with "end up" ?

The website is fetching the pictures from the cdn, pagespeed shrinks them on first fetch but tries to deliver the shrinked cached image from the cdn instead of its own cache on the 2nd fetch.

**Comment by oschaaf** [comment]
By "end up" I meant to ask: does your CDN pull these images from your webserver(s), or do you or some process push these images to the CDN. 
If the CDN uses a pull model, your setup should have worked fine, because the CDN would have been able to fetch `.pagespeed.` urls from your ngx_pagespeed enabled webserver. So I will asume a push model.

If you want images like `http://foo.cnd.com/bar.jpg` to be hosted like `http://mynginxserver.com/bar.pagespeed.xxx.jpg` , you can apply a rewrite domain mapping:
https://modpagespeed.com/doc/domains#mapping_rewrite

Alternatively, you could look into MapProxyDomain, which allows you to rehost any external domain into a subdirectory:
https://modpagespeed.com/doc/domains#MapProxyDomain

hope that helps!

**Comment by wigald** [comment]
Hi,

the images are being pushed to the cdn by ourselfs.

I tried it with MapRewriteDomain.

`pagespeed MapRewriteDomain mynginx.com cdn.mynginx.com`

This doesn't work, images still getting fetched from the cdn like this:

https://cdn.mynginx.com/images/myimage.png.pagespeed.ic.gqBrCHnXJj.webp

**Comment by wigald** [comment]
I think I got it now,

it seems to work with https:// defined in the address.

Looks like this now:

> https://mynginx.com/xxxxxx/xxxxx.aspx:1138: Shrinking image `https://cdn2.mynginx.com/images/myimage.png' (7610 bytes) to `https://mynginx.com/images//xmyimage.png.pagespeed.ic.LI6iYrd3DO.webp' (7024 bytes)


:)

**Comment by oschaaf** [comment]
Yes, if no protocol is specified, `http` is assumed.
Great to hear it's working!

**Comment by wigald** [comment]
OK my boss said renaming those images is seo critical :D So I had to disable the rewriting for now.
Is there a way to cache from my nginx proxy but rewrite the URL to the original one with the original filename ?

**Comment by oschaaf** [comment]
The rewritten urls should be served with a `Link: <..>; rel="canonical"` header, which by my knowledge should negate any SEO impact. Looking at https://github.com/pagespeed/mod_pagespeed/commit/0ea2124fcdb0ae94e25383ac8f689b18edbedd26#diff-f2efeb8aa7e7723c6a359e57bc50117dR595 I don't think pagespeed will add them for you with your configuration, but you could consider adding them yourself.

If you do not want urls to be rewritten at all, you could consider setting the rewrite level to `OptimizeForBandwidth`: https://modpagespeed.com/doc/optimize-for-bandwidth
