### ISSUE TITLE
Images optimization unstable?

### ISSUE THREAD

**Issue by Onyx808** [pagespeed/ngx_pagespeed#1393]
Hello,

I'm learning on how to use nginx PageSpeed, and running a test site, and when checking the test site on PageSpeed Insights I get very mixed results, sometimes it shows that I need to optimize the images and sometimes it doesn't, any idea why this is happening?

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2F138.68.40.223%2F&tab=desktop

My settings:

```
    page speed on;
    pagespeed FileCachePath /var/ngx_pagespeed_cache;

    pagespeed RewriteLevel CoreFilters;
    page speed EnableFilters recompress_images,resize_rendered_image_dimensions,inline_images,prioritize_critical_css,defer_javascript;

    location ~ ".pagespeed.([a-z].)?[a-z]{2}.[^.]{10}.[^.]+" { }
    location ~ "^/ngx_pagespeed_static/" { }
    location ~ "^/ngx_pagespeed_beacon$" { }
```

Thank you!

**Comment by oschaaf** [comment]
Looking at your website, it looks like css/js/images are served without explicit caching directives. The module will re-check the original resources every five minutes, and you may see partially optimized responses while it is doing so.

To improve, you could consider bumping the `ImplicitCacheTtlMs`:
https://modpagespeed.com/doc/system#implicit_cache_ttl

Alternatively, you could consider configuring the module to load resources directly from disk:
https://modpagespeed.com/doc/domains#ModPagespeedLoadFromFile

**Comment by jmarantz** [comment]
Clarifying one point:. Even if you have 5 minute TTL, which is the default
implicit setting, it is no problem as long as you have more than one query
per minute.

This is because PageSpeed will freshen resources in the background after
they are 80% of the way through their lifetime.

The problem only shows up when you have a short TTL and very sparse traffic.

**Comment by Onyx808** [comment]
Ok, so that does mean that every 5 minutes the website will deliver the original images?

Sorry if it sounds dumb, Im new to this =(

**Comment by jmarantz** [comment]
That will be the case if no one visits your site.  If you have a at least
five visitors over the course of your TTL (one per minute for a 5-minute
TTL) then PageSpeed will always serve optimized images.

In other words, PageSpeed is tuned for sites with visitors :)

A workaround is to make a cron-job that runs wget or curl on your site's
pages once a minute, to keep it fresh in PageSpeed's cache.

**Comment by Onyx808** [comment]
@jmarantz thank you! I get it now, it doesn't quite make sense to me tho, traffic tends to fluctuate, so if the site goes without visits for 5 minutes then the next visitor gets not optimized images? can PageSpeed optimize the original images instead?

**Comment by jmarantz** [comment]
PageSpeed doesn't know whether the images and other resources on your site
will continue to be relevant over time, or whether the important resources
on a site will change every 5 minutes.

So it learns this from your traffic.  If there is no traffic then there is
nothing that needs to be refreshed, as far as PageSpeed can tell.

Your have two controls over this: The TTL with which you serve your origin
resources, and the site traffic, which you can generate yourself with cron
jobs to keep the caches fresh, kind of like DRAM refresh.



On Mar 17, 2017 1:42 AM, "Marcos Nobre" <notifications@github.com> wrote:

@jmarantz <https://github.com/jmarantz> thank you! I get it now, it doesn't
quite make sense to me tho, traffic tends to fluctuate, so if the site goes
without visits for 5 minutes then the next visitor gets not optimized
images? can PageSpeed optimize the original images instead?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/pagespeed/ngx_pagespeed/issues/1393#issuecomment-287243580>,
or mute the thread

**Comment by Onyx808** [comment]
@jmarantz thank you so much for your explenation! much appreciate it, I will continue my journey with PageSpeed!

**Comment by oschaaf** [comment]
Added a f.a.q entry for this: https://github.com/pagespeed/mod_pagespeed/commit/7fbc3b0c2788414002b5ab616623c1d13fea9889
