### ISSUE TITLE
Weird results on pagespeed (site) after pagespeed instalation

### ISSUE THREAD

**Issue by DPvic** [pagespeed/ngx_pagespeed#1413]
Hi, 
After some testing we decided to install nginx on our production server. All worked fine but we are getting some strange results on PageSpeed Insights. On some pages it suggests us to optimize the images, even if they are already optimized with jpegtrim and quality downgraded to 85%. This didn't happen before the installation of pagespeed module (nginx).

![captura de pantalla 2017-05-02 a las 16 27 51](https://cloud.githubusercontent.com/assets/28042832/25651383/0367e464-2fe3-11e7-8df7-24be39deeb9a.png)
![bad](https://cloud.githubusercontent.com/assets/28042832/25651909/c974756c-2fe5-11e7-839c-b2fb4ddfb1bf.png)

I cloned the site how site and  tested it through PageSpeed Insights, it passes the same image. I can't see anything strange, the only difference I can see is the header "x-original-content-length: 10880". Also tried to enable "pagespeed TrackOriginalContentLength off;" but there is no documentation and I am not really sure how to use it. These are the results on other server with the same images:

![captura de pantalla 2017-05-02 a las 16 28 00](https://cloud.githubusercontent.com/assets/28042832/25651413/3444f8ba-2fe3-11e7-9bd4-f02bea909770.png)
![bad](https://cloud.githubusercontent.com/assets/28042832/25652004/4c09dbc0-2fe6-11e7-805b-bab1d5a6e7f4.png)

**Comment by Lofesa** [comment]
Hi @DPvic 
Images (and other subresources) are not optimized by pagespeed module as far as you need to auth the domain from where are served.
Try to auth the domain with:
pagespeed Domain https://*.donurmy.es

and pagespeed module don´t work well with relative url like src=//static1..... need to be http or https.

In other hand,  PageSpeed Insights can say that images are not fully optimized even when are optimized by pagespeed module

**Comment by oschaaf** [comment]
@Lofesa have you observed any particular problems with protocol relative urls?

**Comment by Lofesa** [comment]
Yes, in a old version they don´t get optimized.... I don´t remember the exact message but relative to a non auth domain, if I remember well

**Comment by DPvic** [comment]
@oschaaf  At least, the relative protocol url's aren't working with npx_pagespeed 1.11.33.4-0. The image modules only started to work after changing the urls to https and enabling the pagespeed Domain site.com; rule. 

Maybe this is not the proper place tu question... 
As suggested by @Lofesa I enabled the "pagespeed Domain https://*.donurmy.es" inside my test server. Images are been served ok from the static server, but the cache is also been generated inside the static server. What disturbs me is that I haven't allowed or marked the test server enywhere inside the static server. 
Does this mean that any site can generate the images inside the cache dir of my static server just by making the proper request?
Also the resized images are always served with the header "max-age=300,private" which is really low. I read that it could be caused by a small amount of request so I tried with 30~requests from 4 different webrowsers and the cache never changes.

**Comment by Lofesa** [comment]
Hi @DPvic 
Relative to the max-age=300,private.... this header is for html not images. Had you set the LoadFromFile directive? But the "private" part I think is set by your server config.
Have you enabled the extend cache directive?
Is the "Pagespped on" directive set on the http{} block? if yes, pagespeed is on on all server{}
What path have the pagespeed FileCachePath directive? In this path is where cache is created
The pagespeed cache is populated from any request to server where pagespeed is set to on and stored where the pagespeed FileCachePath is set.
If you post here the whole nginx config here (whith paths, ip and so anonymized) I can better understand what is happend with your config.

P.D. perdona mi ingles pesimo

**Comment by DPvic** [comment]
@Lofesa You are right, it was enabled inside the http{} block, I completely forgot about it. 


```
 http {
 include mime.types;
 default_type application/octet-stream;
 log_format main '$remote_addr - $remote_user [$time_local] $request '
  '"$status" $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for" $msec $request_length $request_time';

 gzip on;
 gzip_http_version 1.0;
 gzip_comp_level 2;
 gzip_proxied any;
 gzip_min_length 1100;
 gzip_buffers 16 8k;
 gzip_types text/plain text/html text/css application/x-javascript application/json text/xml application/xml application/xml+rss text/javascript application/javascript;

 gzip_disable "MSIE [1-6].(?!.*SV1)";
 gzip_vary on;

   pagespeed on;
   pagespeed FileCachePath /var/ngx_pagespeed_cache;
  } 
```

```
server {
        listen 443 ssl http2;
        server_name example.com

        # root, ssl, etc

	pagespeed on;
	pagespeed FileCachePath /var/ngx_pagespeed_cache;
	pagespeed EnableFilters remove_comments;
	pagespeed EnableFilters prioritize_critical_css;
        pagespeed EnableFilters inline_google_font_css;       
        pagespeed Domain https://*.example.com;
	pagespeed EnableFilters resize_images;
        pagespeed ImageRecompressionQuality 100;

	location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
		 add_header "" "";
	}

	location ~ "^/pagespeed_static/" { }
	location ~ "^/ngx_pagespeed_beacon$" { }

        location ~* \.(eot|otf|ttf|woff|svg)$ {
            add_header Access-Control-Allow-Origin *;
        }
        location ~* \.(?:jpg|jpeg|png|gif|ico|css|js)$ {            
            expires 1y;
            add_header Cache-Control "public";
        }
}



server {
        listen 443 ssl http2;
        server_name  static1.example.com static2.example.com
        # root, ssl, etc

        location ~* \.(eot|otf|ttf|woff|svg)$ {
            add_header Access-Control-Allow-Origin *;
        }

        location ~* \.(?:jpg|jpeg|png|gif|ico|css|js)$ {
            expires 1y;
            add_header Cache-Control "public";
        }

        location ~ .*php {
            deny all;
        }

        location ~ /\.ht {
            deny  all;
        }
}
```

Currently the resized images are created after some request (5-10), at that point Pagespeed Insight is giving a good score, but after some time (15-20 min) it drops agains and the images are served from the source instead of the resized.

**Comment by Lofesa** [comment]
Hi @DPvic 
As far I understand, you are using a file cache in /var/ngx_pagespeed_cache, configured at http{} block thus all cached resources are here, from you main server and your static server.
With this config you are using the default [RewriteLevel CoreFilters](https://modpagespeed.com/doc/config_filters#level) plus the filters enabled in the main server{} block, that work only in this block thus filters not in the default CoreFilters are not applied to files in the static server ( For example you have enabled ImageRecompressionQuality 100 in the main server block but not in the static block thus images served from this are served whit the default ImageRecompressionQuality 85) thus I advise you to review what image filters are out of the default CoreFilters and apply it to both servers, for that put the directives in the http{} block. Basically directives in http{} block are apllied to both server and directives in server{} block only on that block.
As I stated before, the cache is populated by any request to a server with "PagSpeed on".
Perhaps you need to enable "pagespeed FinderPropertiesCacheExpirationTimeMs num.milisec" and "pagespeed FinderPropertiesCacheRefreshTimeMs num.milisec" to try to "enlargue" the time files are stored in cache, but perhaps you need to set a big cache size because if the size is small the files cached are evicted to make room to the new files (you can read it [here](https://modpagespeed.com/doc/system)) 

In your config you have set the pagespeed FileCachePath 2 times to the same path, you can leave only 1 at http{} block and have only 1 cache for main and static sites with the apropiate size.
In this config ( w/o memcached or redis) you need to configure a shared memory metadata cache as stated in the last link above.

Try these changes at see how it work and comment here.
Greetings.

**Comment by DPvic** [comment]
@Lofesa 

Sorry for the delay, it seems to work fine, really appreciate your help!
