### ISSUE TITLE
Pagespeed directive not found

### ISSUE THREAD

**Issue by isaacgoodman** [pagespeed/ngx_pagespeed#1426]
I'm using the automated script for NGINX on Ubuntu 17.04. How can I install it properly?

**Comment by isaacgoodman** [comment]
I also already have an existing NGINX setup.

**Comment by oschaaf** [comment]
Did you see https://modpagespeed.com/doc/build_ngx_pagespeed_from_source? 

I think you have two options:
1. Replace the installed nginx binary with a version that you build yourself, which has ngx_pagespeed installed plus the other features you need. 
2. Compile ngx_pagespeed as a dynamic module [1] and configure the currently installed nginx  to load that.  This may be a bit of a hassle, because you have to make sure that a bunch of configure flags match the ones used to build the system installed nginx binary, to ensure that the resulting compiled dynamic module is compatible. Nginx 1.11.5 introduced `--with-compat` which aims to make this easier, but your nginx version is probably 1.10.3. 
(Looking at https://www.nginx.com/resources/wiki/start/topics/tutorials/install/ I think it may be possible to update the installed nginx version to the mainline version instead of the stable version using the package manager, but I am not sure if `--with-compat` has been enabled there)

**Comment by isaacgoodman** [comment]
OK. Thanks!
