### ISSUE TITLE
pagespeed RedisServer as a Variable? 

### ISSUE THREAD

**Issue by ciarans** [pagespeed/ngx_pagespeed#1485]
When you using Redis as the caching backend the documentation states to set the Redis host as 
```
pagespeed RedisServer "host:port";
```

My Redis host and port is passed as a environment variable.  So I set it like this;

```
set $redis_connect "127.0.0.1:6379"
```

I have turned Script variables on however I have  tried the following and it cant connect;

```
pagespeed RedisServer "$redis_connect";
pagespeed RedisServer $redis_connect;
```

Is this possible?

**Comment by oschaaf** [comment]
I think that won't work, even if you have turned on ngx_pagespeed's script variable processing. The reason is that the script variable processing will only be applied to options that can be changed on the fly at request processing time, and `RedisServer` is not included in those (instead it is only interpreted at server startup time, while processing the `root{}` and `server{}` configuration blocks).

**Comment by ciarans** [comment]
If anyone else comes across this, I managed to simply sed the file with the environment variable
