### ISSUE TITLE
Support the equivalent of ModPagespeedIf spdy

### ISSUE THREAD

**Issue by oschaaf** [pagespeed/ngx_pagespeed#821]
From the list:
The "different options for clients connecting over SPDY" are Apache-only, unfortunately...

It would be great to have ngx_pagespeed SPDY-aware

**Comment by jeffkaufman** [comment]
This was released in [1.9](https://developers.google.com/speed/pagespeed/module/release_notes#release_1.9.32.1-beta) and is [documented](https://developers.google.com/speed/pagespeed/module/domains#LoadFromFileScriptVariables).

**Comment by sunnybear** [comment]
map $spdy $disabled_filters {
~1 "list,of,filters,to,disable";
default "";
}

**Comment by jeffkaufman** [comment]
@sunnybear I'm not sure what you're saying.

**Comment by oppianmatt** [comment]
Sorry to comment on an old issue but I don't think this is documented. First up the docs at https://developers.google.com/speed/pagespeed/module/https_support#spdy_configuration say it's for apache only. But following this thread it implies that we can use script variables if we put the directive `pagespeed ProcessScriptVariables on;`

So I've tried a few different combinations and can't get it to work. I've tried:

```
location / {
    ....snip

            set $disablefilters "";

            if ($spdy) {
                set $disablefilters "combine_css,combine_javascript";
            }

            pagespeed DisableFilters $disablefilters;
}
````
But get this error message:

```
2015/03/31 12:00:27 [warn] 9156#0: [ngx_pagespeed 1.9.32.2-4321] [0331/120027:WARNING:google_message_handler.cc(38)] Invalid filter name: $disablefilters
2015/03/31 12:00:27 [emerg] 9156#0: "pagespeed" directive "DisableFilters $disablefilters" Failed to disable some filters. in /etc/nginx/conf.d/pitchup.conf:465
```

So seems you can't use a script var in the DisableFilters section. 

I know the $spdy part is valid since I have:

```
proxy_set_header    X-Spdy                  $spdy;
```

Wrapping the `$disablefilters` with quotes doesn't help, same error. 

The only thing that works is:

```
            if ($spdy) {
                pagespeed DisableFilters "combine_css,combine_javascript";
            }
```

But that suffers from the if issue @PiotrSikora has stated. 

If we could use a script variable like @PiotrSikora is suggesting (and pull request #822 is adding) then we don't need an `if` which is what @sunnybear is showing. Instead of an if, that can be replaced with a map which sets the variable. 

```
map $spdy $disabled_filters {
  ~1 "list,of,filters,to,disable";
  default "";
}
pagespeed DisableFilters "$disabled_filters";
```

That's how to write it without an if at all. But I can't get the script variable part working and also the documentation on it being only apache needs updating. 

Note this was with nginx_1.6.2+nps1.9.32.2_amd64.deb

Updating to latest version just to be sure, same error. Putting it in the server block same error:

```
stderr: nginx: [warn] [ngx_pagespeed 1.9.32.3-4448] [0331/152422:WARNING:google_message_handler.cc(38)] Invalid filter name: $disablefilters
nginx: [emerg] "pagespeed" directive "DisableFilters $disablefilters" Failed to disable some filters. in /etc/nginx/conf.d/pitchup.conf:477
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by oppianmatt** [comment]
might be good to also document what filters are recommended to be disabled for spdy http://chimera.labs.oreilly.com/books/1230000000545/ch13.html#_dual_protocol_application_strategies

**Comment by oschaaf** [comment]
@oppianmatt Scripting `EnableFilters` and 'DisableFilters`  has landed on trunk-tracking via https://github.com/pagespeed/ngx_pagespeed/pull/822, but not in 1.9.x
It is a tiny source change, so you might be able to patch it in

**Comment by oppianmatt** [comment]
ahh that would explain it, thanks @oschaaf I'll just wait for the release and use the evil if until then. And then change to the map when it's ready.
