### ISSUE TITLE
nginx FetchHttps doesn't work

### ISSUE THREAD

**Issue by ton31337** [pagespeed/ngx_pagespeed#830]
Hello,

nginx 1.7.4
ngx_pagespeed 1.9.32.1
gcc 4.4
Ubuntu

why I see such message inside error_log:

2014/10/15 08:38:30 [info] 11010#0: [ngx_pagespeed 1.9.32.1-4238] [1015/083830:INFO:google_message_handler.cc(35)] Could not rewrite resource in-place: https://www.xxx.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/s/a/saw_it_liked_it_told_granny_got_it_tshirt.jpg_colorLightPinkheight480width480.jpg
2014/10/15 08:38:30 [info] 11010#0: [ngx_pagespeed 1.9.32.1-4238] Trying to serve rewritten resource in-place: https://www.xxx.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/s/a/saw_it_liked_it_told_granny_got_it_tshirt.jpg_colorLightPinkheight480width480.jpg
2014/10/15 08:38:30 [info] 11010#0: [ngx_pagespeed 1.9.32.1-4238] HTTPCache key=https://www.xxx.com/media/catalog/product/cache/1/small_image/210x/9df78eab33525d08d6e5fb8d27136e95/s/a/saw_it_liked_it_told_granny_got_it_tshirt.jpg_colorLightPinkheight480width480.jpg fragment=xxx.com: remembering not-found status for 296 seconds.

configuration is:

  pagespeed FetchHttps enable;
  pagespeed SslCertDirectory /etc/ssl/certs;
  pagespeed RespectXForwardedProto on;

Everything works perfect with HTTP. But with HTTPS pagespeed can't rewrite resources using HTTPS. 

By the way I tried to set this header before proxy_pass to pagespeed, but no success:
add_header X-Forwarded-Proto $scheme;

Any ideas?

Donatas.

**Comment by ciarans** [comment]
@ton31337 @oschaaf Has this been resolved as Im getting exactly the same problem;

http://www.simplemarket.co.uk/bitnami/banner.js compresses the JS

however when using HTTPS

https://www.simplemarket.co.uk/bitnami/banner.js does not and returns

```std
2016/12/13 13:29:21 [info] 17#0: [ngx_pagespeed 1.11.33.3-0] Trying to serve rewritten resource in-place: https://www.simplemarket.co.uk/bitnami/banner.js
2016/12/13 13:29:21 [info] 17#0: [ngx_pagespeed 1.11.33.3-0] Cache entry is expired: https://www.simplemarket.co.uk/bitnami/banner.js (fragment=simplemarket.co.uk)
2016/12/13 13:29:21 [info] 17#0: [ngx_pagespeed 1.11.33.3-0] Could not rewrite resource in-place because URL is not in cache: https://www.simplemarket.co.uk/bitnami/banner.js
```

**Comment by oschaaf** [comment]
@ciarans when I take look at https://www.simplemarket.co.uk/bitnami/banner.js I do get a minified version.. 
Is there a CDN or reverse proxy caching the unminified version?

In any case, I don't think your problem is related to this particular issue, which ended up being a problem in https fetching with Serf (SERF_SSL_CERT_UNKNOWN_FAILURE). The log warnings you posted are about in-place resource optimization, which does not rely on https fetching.

**Comment by ciarans** [comment]
@oschaaf Thanks for clearing that up. I'm not 100% sure to be honest. 

I am using a reverse proxy however.

You are correct that it is minified at https://www.simplemarket.co.uk/bitnami/banner.js  but this because I made a curl request to http://www.simplemarket.co.uk/bitnami/banner.js to minify the contents.
