### ISSUE TITLE
Images return 404 at first time

### ISSUE THREAD

**Issue by herlon214** [pagespeed/ngx_pagespeed#871]
At the first time that the page is loaded the images don't show. Only at the second time.
Am I wrong at the code or it's a ngx_pagespeed issue?

Part of the ```nginx.conf```

```ssh
pagespeed on;
	pagespeed Domain *;
        pagespeed FileCachePath /usr/local/nginx/pagespeed_cache;
	pagespeed Statistics on;
	pagespeed StatisticsLogging on;
	pagespeed LogDir /var/log/pagespeed;
	pagespeed AdminPath /pagespeed_admin;
	pagespeed BeaconUrl "http://www.mydomain.com.br/ngx_pagespeed_beacon";
	pagespeed MapRewriteDomain http://www.mydomain.com.br/ngx_pagespeed *;
	pagespeed Allow wildcard_spec;
	pagespeed RespectVary on;
	
	pagespeed Disallow "*.css*";
	pagespeed Disallow "*/fonts/*";
	pagespeed Disallow "*/banners/*";
	pagespeed Disallow "*.png*";	
	pagespeed Disallow "*.js*";
	pagespeed Disallow  "*.gif*";


	# enable CoreFilters
        pagespeed RewriteLevel PassThrough;

        # disable particular filter(s) in CoreFilters

        # enable additional filter(s) selectively
	pagespeed EnableFilters combine_css,rewrite_images;
	pagespeed EnableFilters recompress_jpeg;
	#pagespeed EnableFilters convert_gif_to_png;
	pagespeed EnableFilters convert_png_to_jpeg;
	pagespeed EnableFilters rewrite_css,rewrite_javascript;
	pagespeed EnableFilters rewrite_domains;


	
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       8080;
        server_name  localhost www.mydomain.com.br mydomain.com.br;
        #charset koi8-r;
        #access_log  logs/host.access.log  main;

	# Pagespeed

        location ~ "\.pagespeed\.([a-z]\.)?[a-z]{2}\.[^.]{10}\.[^.]+" {
                add_header "" "";
        }
	location /dist {
		if ($request_uri ~* ".(jpg|jpeg|gif|gz|zip|flv|rar|wmv|avi|css|swf|png|htc|ico|mpeg|mpg|txt|mp3|mov|js|svg|woff|ttf|eot)(\?v=[0-9.]+)?$") {
                        expires 30d;
                        access_log off;
                        break;
                }

		root /home/ec2-user/www/path/to/app/public/;
	}
	location ~ "^/pagespeed_static/" {  }
        location ~ "^/ngx_pagespeed_beacon$" { }
	location ~ ^/pagespeed_admin {
  		allow 127.0.0.1;
  		deny all;
	}

	
	location / {
		proxy_set_header    Host       $http_host;              
    		proxy_set_header X-Real-IP $remote_addr;
    		#proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;   
    		proxy_set_header X-Forwarded-For $http_x_forwarded_for;
                proxy_pass      http://127.0.0.1:3000;
		
        }

```

I'm using Varnish at port 80 sending request to Nginx at port 8080 and send proxy to NodeJS at port 3000.

Anyone can help me?

**Comment by jeffkaufman** [comment]
Why do you have `pagespeed Domain *`?  That tells pagespeed that it can rewrite any url it sees.  For example, if your page were to reference `jquery.com/jquery.js` then pagespeed would be willing to fetch `jquery.js` and optimize it, rewriting the url to `jquery.com/jquery.js.pagespeed.jm.HASH.js` even though `jquery.com` isn't running pagesped and won't understand this.  You should only list in `Domain` sites that are actually running pagespeed.

What is `pagespeed Allow wildcard_spec` supposed to do?  `wildcard_spec` is just a placeholder.

`pagespeed MapRewriteDomain http://www.mydomain.com.br/ngx_pagespeed *` doesn't make sense.  That will rewrite urls from `jquery.com/jquery.js` to `http://www.mydomain.com.br/ngx_pagespeed/jquery.js.pagespeed.jm.HASH.js` but it won't actually make `http://www.mydomain.com.br/ngx_pagespeed/jquery.js.pagespeed.jm.HASH.js` proxy `jquery.com/jquery.js` and you'll get 404s.  Maybe you want `MapProxyDomain`?  But then you need to specify which domains you want to proxy onto your domain; there's currently no way to tell pagespeed to just proxy everything onto your domain.

You have:
```
pagespeed Disallow "*.css*";
pagespeed Disallow "*.png*";    
pagespeed Disallow "*.js*";
pagespeed Disallow  "*.gif*";
```
this won't let pagespeed optimize any css, png, js, or gif files.  Is that intentional?

There are several serious things wrong with your config, but none of them should actually be leading to images that don't load on the first request.  If this problem persists after fixing the other issues, we can look into it.

**Comment by herlon214** [comment]
@jeffkaufman How should I use the MapProxyDomain?
The situation is:
I want to the pagespeed optimize external contents too. On my website I show a lot of images from external urls (they aren't optimized).
I had a problem with png images too.

**Comment by jeffkaufman** [comment]
PageSpeed can optimize resources on external sites, but you need to explicitly list them.  Why?  Because PageSpeed needs to know where in your url space to store them.  For example, if your site includes images from `foo.example.com`, `bar.example.com`, and `baz.example.com`, and you're comfortable using `/foo`, `/bar/`, and `/baz` for them, you could write:

```
pagespeed MapProxyDomain foo.example.com/ you.example.com/foo;
pagespeed MapProxyDomain bar.example.com/ you.example.com/bar;
pagespeed MapProxyDomain baz.example.com/ you.example.com/baz;
```

You do need to be sure you trust the operators of the external sites, because [GIFAR](http://hackaday.com/2008/08/04/the-gifar-image-vulnerability/)-style attacks can give people XSS on your website.

Doc: https://developers.google.com/speed/pagespeed/module/domains#MapProxyDomain

You generally don't need to customize the Beacon url.  That should work as it is.  If you're having a problem with it, can you open a separate bug?

Could you open a new bug for the problem you're having with PNG?

**Comment by jeffkaufman** [comment]
If you have more questions feel free to reopen.
