### ISSUE TITLE
include_js_source_maps with combine_javascript

### ISSUE THREAD

**Issue by oppianmatt** [pagespeed/ngx_pagespeed#883]
Trying to get source maps along with combined javascript files. Source map specs say you can specify multiple files in a map for a combined js. Trouble is doesn't seem pagespeed supports this (unless I'm mistaken).

```
    pagespeed EnableFilters combine_javascript;
    pagespeed EnableFilters include_js_source_maps;
    pagespeed UseExperimentalJsMinifier on;
```

Has the javascript combined, but the source map comment is not there. But when you disable the combine_javascript (since it's enabled by default). You do get source maps, but one for each file.

```
//# sourceMappingURL=http://media.dev.pitchup.co.uk/static/js/modernizr.js.pagespeed.sm.2fAMAJFW5f.map
```

Shouldn't it either combine the javascript and create a source map for the combined javascript, or have a warning/error in the log if you try enable both filters (and update the docs to say you can't have both).

**Comment by jeffkaufman** [comment]
@sligocki

**Comment by sligocki** [comment]
You are correct. We do not create source maps for combine js. Unfortunately, because of the way that combine js works, I don't think it would be possible to use source maps. As you pointed out, it would be possible if we simply concatenated the js files and loaded them with a single <script> tag. However, that is not combine js works. Instead, it converts each js file into a string, creates the combine file with this list of strings, then evals each string at the location the original js had been. AFAIK, there is no way to use source maps from eval-ed js.

**Comment by sligocki** [comment]
You are correct. We do not create source maps for combine js. Unfortunately, because of the way that combine js works, I don't think it would be possible to use source maps. As you pointed out, it would be possible if we simply concatenated the js files and loaded them with a single <script> tag. However, that is not combine js works. Instead, it converts each js file into a string, creates the combine file with this list of strings, then evals each string at the location the original js had been. AFAIK, there is no way to use source maps from eval-ed js.

**Comment by sligocki** [comment]
You are correct. We do not create source maps for combine js. Unfortunately, because of the way that combine js works, I don't think it would be possible to use source maps. As you pointed out, it would be possible if we simply concatenated the js files and loaded them with a single script tag. However, that is not combine js works. Instead, it converts each js file into a string, creates the combine file with this list of strings, then evals each string at the location the original js had been. AFAIK, there is no way to use source maps from eval-ed js.

**Comment by jeffkaufman** [comment]
It sounds like this isn't something we're going to be able to support.
