### ISSUE TITLE
SunOS

### ISSUE THREAD

**Issue by leemr** [pagespeed/ngx_pagespeed#923]
When I try and compile in PageSpeed to nginx, I get this error:

adding module in ../ngx_pagespeed-1.9.32.3-beta
OS not supported: SunOS

**Comment by jeffkaufman** [comment]
That's correct; ngx_pagespeed doesn't currently support SunOS.  This is because it depends on PSOL, a part of mod_pagespeed, and that doesn't support SunOS either.  We're not currently planning to port to SunOS, but if someone else is interested in doing the porting I'd be happy to review patches and answer questions.
