### ISSUE TITLE
Last-Modified will be overwritten

### ISSUE THREAD

**Issue by bikalexander** [pagespeed/ngx_pagespeed#958]
Hello everybody,

as soon as I turn off this option:

ModPagespeedModifyCachingHeaders off;

unfortunately overwritten in headers "Last-Modified" and disappears.

This issue has already been discussed in mod_speed:
https://github.com/pagespeed/mod_pagespeed/issues/652

Is there any possible solution?

Use current stable version + nginx 1.8.0

Thanks in advance!

**Comment by bikalexander** [comment]
sorry have, of course, meant when the option is turned off, then everything is in order.
If the option is on, then "Last-Modified" suppressed.

Thanks in advance!

**Comment by jeffkaufman** [comment]
Are you saying that by default PageSpeed is modifying your caching headers, including `LastModified`?  And that to get PageSpeed to not make these changes you've set `ModifyCachingHeaders off`, which is working?  This all sounds like what's supposed to happen.  Could you describe the problem this is causing you?

**Comment by bikalexander** [comment]
Are you saying that by default PageSpeed is modifying your caching headers, including LastModified? 

yes

And that to get PageSpeed to not make these changes you've set ModifyCachingHeaders off, which is working? 

yes


What information do you broke?

here is a precaution my configuration:
http://pastebin.com/2z1GnvE6

Testing, I do it with:
  curl -I http://xxxxx.xxx

**Comment by jeffkaufman** [comment]
I'm still not sure how this is causing you a problem.  PageSpeed makes many optimizations to pages, including modifying the caching headers.  Because we're setting a `Cache-Control` header of  zero seconds we don't need a `Last-Modified` header; why do you want PageSpeed to keep it?

**Comment by bikalexander** [comment]
Well, yes it is recommended on the homepage:
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
and this version is better suited for my site.

This uses also Wikipedia:
http://last-modified.com/en/

Or did I wrong opinion?

Thanks in advance!

**Comment by bikalexander** [comment]
I have read on several sites that Google crawler would like this too, is it true or not?

**Comment by bikalexander** [comment]
Hi Jeff Kaufman,

as I understand it, it will probably still used by Google Crawler:
http://www.google.ru/support/enterprise/static/gsa/docs/admin/72/gsa_doc_set/admin_crawl/introduction.html#1076354

Yandex also used this method

**Comment by jeffkaufman** [comment]
The standard use of `Last-Modified` is so people who have a stale cached version can just check back with the server to see if there's an update, instead of redownloading.  So I would serve html like:

    HTTP/1.1 200 OK
    Cache-control: max-age=0
    Last-Modified: Sun, 19 Apr 2015 19:01:00 GMT

And then when fetching the page again the browser would send:

    GET / HTTP/1.1
    Host: example.com
    If-Modified-Since: Sun, 19 Apr 2015 19:01:00 GMT

If the page had been modified, the full page would be sent down, otherwise the server would respond with:

    HTTP/1.1 304 Not Modified
    Cache-control: max-age=0
    Last-Modified: Sun, 19 Apr 2015 19:01:00 GMT

A similar process happens with all the resources on the page, with some amount of valid cache lifetime and then a system for checking back if they've changed.

Instead of this caching negotiation PageSpeed uses longcaching.  The way this works is it rewrites all the resources to have a hash of their contents in their url, and then serves them for a very long time.  So your html would change from:

    <img src="example.jpg">
    <script src="example.js">

To:

    <img src="example.jpg.pagespeed.ce.HASH.jpg">
    <script src="example.js.pagespeed.ce.HASH.js">

This makes resource downloading much more efficient, because the browser never needs to check back with the server to see whether a resource is still valid.

Because PageSpeed makes this change, however, the legal `Last-Modified` header to set on the page would have to be the most recent `Last-Modified` header out of all the referenced resources.  For speed, however, PageSpeed works in a streaming fashion, so it has to send out the headers before it's necessarily seen what all the resources the html references are, and so it doesn't know what the most recent `Last-Modified` header is.  This means it can't set a `Last-Modified` header.

On balance this is still a big improvement to speed because it lets your users avoid a lot of expensive round trips for revalidating resources without adding any round trips to html fetching.

If you set `ModifyCachingHeaders off` PageSpeed will not change the `Last-Modified` or `Cache-Control` headers but will still do cache extension (longcaching).  This means if you change your images/css/js then people might not see the changed versions until you change your html as well, updating its `Last-Modified` date.

**Comment by bikalexander** [comment]
Hi jeffkaufman,

sorry have to ask again, as I unfortunately English not so good can:

This means that the method with the hashes is better than with Last-Modified?

And I understand correctly that the browser will download only the files with changed hash?

Thanks in advance!

**Comment by jeffkaufman** [comment]
> This means that the method with the hashes is better than with Last-Modified?

Yes.

> And I understand correctly that the browser will download only the files with changed hash?

Wes, because we include a `Cache-Control` header on these files saying that they're valid for an extremely long time, with no requirement to check back with the server for updates.

**Comment by bikalexander** [comment]
great, thank you!

It would be nice if jrmand would complement this info on the homepage:

https://developers.google.com/speed/docs/insights/LeverageBrowserCaching
