### ISSUE TITLE
X-Accel-Redirect requests remove Content-Disposition header

### ISSUE THREAD

**Issue by WesCossick** [pagespeed/ngx_pagespeed#980]
Nginx built without PageSpeed retains the `Content-Disposition` header, however, `ngx_pagespeed` appears to remove this header from the response headers delivered to the client. This is only for requests using the `X-Accel-Redirect` header.

I'm currently setting the header with PHP through PHP-FPM.

**Comment by FujiMakoto** [comment]
I referenced this issue here:
https://github.com/pagespeed/ngx_pagespeed/issues/826#issuecomment-66034496

But I'm not sure the linked bug report is actually relevant to the issue. Either way, I can confirm this is a problem. As mentioned in the above comment, if you need a quick fix for this, you can simply have add your X-Accel-Redirect download URI's as disallow's, this way PageSpeed won't interfere with the headers.

**Comment by jeffkaufman** [comment]
Yes, for now setting `Disallow` for these resources is the best workaround.  We're intending to fix this with https://github.com/pagespeed/ngx_pagespeed/issues/981

**Comment by WesCossick** [comment]
Disallowing it fixes the issue. Definitely recommend the change proposed in #981.

**Comment by jeffkaufman** [comment]
Sounds good!  The #981 fix is the plan.

**Comment by crowell** [comment]
closed by 4bef2af22c95bede9794879971d5f9bfeeb337da
